springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
api-docs:
  version: 1.0.0
  title: API de Facturas
  description: Descripción del proyecto y sus funcionalidades.
  contact:
    name: Javier
    email: javier_alegre@itrsa.com.ar

  datasource:
    url: jdbc:mysql://localhost:3306/utn_stock?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: javier
    password: cng10ja
    driver-class-name: com.mysql.cj.jdbc.Driver

  doc:
    api-docs:
      title: API de Facturas
      description: Descripción del proyecto y sus funcionalidades.
      version: 1.0.0
      contact:
        name: Javier
        email: javier_alegre@itrsa.com.ar
